site_name: My Docs
site_url: https://carloslopezsoto.github.io/DocsPrincipal
theme:
   name: 'material'
   config:
    extra:
      auth: true
   language: es
   palette:
      scheme: 'slate'
      primary: 'indigo'
      accent: 'indigo'
      features:
        - navigation.tabs
      icon:
        logo: 'material/library'
        repo: 'material/library'

   favicon: 'path/to/favicon.ico'
      
plugins:
  - search
  - simple
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      nav_repos:
        - name: docs-principal
          import_url: https://github.com/CarlosLopezSoto/DocsPrincipal?branch=main
          imports: [README.md]
        - name: repo-1
          import_url: https://github.com/CarlosLopezSoto/DocsRepo1?branch=main
          imports: [README.md]
nav:
  - DocsPrincipal:
      - Home: docs-principal/README.md
  - Repo1: repo-1/README.md

simple:
  auth:
    provider: github
    client_id: ${{ secrets.CLIENT_ID }}
    client_secret: ${{ secrets.CLIENT_SECRET }}
