site_name: My Docs

nav_repos:
        - name: backstage
          import_url: https://github.com/backstage/backstage
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
            docs/publishing.md, docs/integrations/index.md, /README.md,
            # asset files needed
            docs/assets/*
            ]
        - name: fast-api
          import_url: https://github.com/tiangolo/fastapi
          imports: [docs/en/docs/index.md]

nav:
  - Home: index.md
  - Repos:
    - 'https://github.com/CarlosLopezSoto/DocsPrincipal/blob/main/README.md'
    - 'https://github.com/CarlosLopezSoto/DocsRepo1/blob/main/README.md'
    - 'https://github.com/CarlosLopezSoto/DocsRepo2/blob/main/README.md'

theme: readthedocs