site_name: My Docs
theme:
   name: 'material'
   palette:
      scheme: 'slate'
      primary: 'indigo'
      accent: 'indigo'
      features:
        - navigation.tabs
      icon:
        logo: 'material/library'
        repo: 'material/library'

   favicon: 'path/to/favicon.ico'

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
      
plugins:
  - search
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      nav_repos:
        - name: docs-principal
          import_url: https://github.com/CarlosLopezSoto/DocsPrincipal?branch=main
          # forward slash is needed in '/README.md' so that only the README.md in the root
          # directory is imported and not all README.md files.
          imports: [
             README.md
            ]
        - name: repo-1
          import_url: https://github.com/CarlosLopezSoto/DocsRepo1?branch=main
          imports: [README.md]
nav:
  - DocsPrincipal:
      - Home: docs-principal/README.md
  - Repo1: repo-1/README.md

