name: Build and Deploy Docs

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material mkdocs-multirepo-plugin 

      - name: Build Docs
        run: mkdocs build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install Dependencies
        run: bundle install

      - name: Set up Jekyll Auth
        uses: jekyll-auth/jekyll-auth-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          oauth_client_id: ${{ secrets.CLIENT_ID }}
          oauth_client_secret: ${{ secrets.CLIENT_SECRET }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site
